name: code_challenge
description: Events App.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ">=0.12.0+2 <0.14.0"
  provider: ^3.2.0
  intl: ^0.15.8
  cached_network_image: ">=1.1.3 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/event_dummy.jpg
